#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(touch)==0)
	{
		motor[motorB]=20;
		motor[motorC]=20;
	}
	motor[motorB]=75;
	motor[motorC]=75;
	wait1Msec(10000);
}
