#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Revised Team B Sentry Simulation API with REMbot.c"


task main()
{
	for (int l = 1 ; l <= 4 ; l++) //This makes the program run for one whole lap around the object.
		{
			moveForward(36); // go forward 36 inches
			turnRight();
		}
}
