#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Revised Team B Sentry Simulation API with REMbot.c"






task main()
{
while (SensorValue (touch) != 1) //in order to create an ongoing loop
	{
		moveForward(36); // go forward 36 inches
		turnRight();
	}
}
