#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard                !!*//
// This is for the NXT model, not TETRIX

/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

string direction = "left";
void moveForward(int ammount);
void turn(string direction);
void turnLeft();
void turnRight();

task main()
{
	moveForward(1800);
	turnLeft();
	moveForward(1200);
	turnRight();
	moveForward(900);
	turnRight();
	moveForward(675);

}

void moveForward(int ammount)
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;

	while(nMotorEncoder[motorC] < ammount)
		{
			motor[motorB] = 50;
	  	motor[motorC] = 50;
  	}
}

void turnLeft()
{
	string direction = "left";
	turn(direction);
}

void turnRight()
{
	string direction = "right";
	turn(direction);
}

void turn(string direction)
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	if(direction == "left")
		{
			while(nMotorEncoder[motorB] < 540)
				{
					motor[motorC] = 0;
			  	motor[motorB] = 50;
		  	}
		}
	else
		{
			while(nMotorEncoder[motorC] < 540)
				{
					motor[motorC] = 50;
			  	motor[motorB] = 0;
		  	}
		}


}
