#pragma config(StandardModel, "REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveForward();
void turnRight();
void turn(string direction);
void doLap(int numberOfLaps);
void moveOneSideAndTurn();
int rightAngleTurnValue = 510;



task main()
{
doLap(2);
}


void doLap(int numberOfLaps)
{
	while(numberOfLaps > 0)
	{
		int numberOfTimes = 0;
		while(numberOfTimes < 5)
		{
			moveOneSideAndTurn();
			numberOfTimes = numberOfTimes + 1;
		}
		numberOfLaps--;
	}
}

void moveOneSideAndTurn()
{
	moveForward();
	turnRight();
}

void moveForward()
{
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(4950);
}


void turnRight()
{
	string direction = "right";
	turn(direction);
}

void turn(string direction)
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	if(direction == "left")
		{
			while(nMotorEncoder[motorB] < rightAngleTurnValue)
				{
					motor[motorC] = 0;
			  	motor[motorB] = 50;
		  	}
		}
	else
		{
			while(nMotorEncoder[motorC] < rightAngleTurnValue)
				{
					motor[motorC] = 50;
			  	motor[motorB] = 0;
		  	}
		}


}
