#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightInactive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is for the NXT model, not TETRIX

/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

void moveToNextLine();
void moveToBlackLineAndBack(int numberOfLines);
void moveToPreviousLine();
void stopMotor(int interval);


int speed = 50;

task main()
{
	// move to first line and back
     moveToBlackLineAndBack(1);
	// move to second line and back
			moveToBlackLineAndBack(2);
	// move to third line and back
			moveToBlackLineAndBack(3);
	// move to fourth line and back
			moveToBlackLineAndBack(4);
	// move to fifth line and back
			moveToBlackLineAndBack(5);


}

	void moveToNextLine(){
		// if already on a black line move off it
		while(SensorValue[light] < 40){
			motor[leftMotor] = speed;
			motor[rightMotor] = speed;
			wait1Msec(1);
		}
		// now move to the next black line
		while(SensorValue[light] > 40){
			motor[leftMotor] = speed;
			motor[rightMotor] = speed;
			wait1Msec(1);
		}
			motor[leftMotor] = speed;
			motor[rightMotor] = speed;
			wait1Msec(200);
		stopMotor(200);
}

	void moveToBlackLineAndBack(int numberOfLines){
	// 1 is added as the robot has crossed the line and needs to
	// count it when going back
	int lineCount = numberOfLines + 1;
		while( numberOfLines > 0){
			moveToNextLine();
			numberOfLines--;
		}
		while( lineCount > 0){
			moveToPreviousLine();
			lineCount--;
		}

}

void moveToPreviousLine()
	{
		// if already on a black line move off it
		while(SensorValue[light] <= 50){
			motor[leftMotor] = -speed;
			motor[rightMotor] = -speed;
			wait1Msec(1);
		}
				while(SensorValue[light] > 50){
				motor[leftMotor] = -speed;
				motor[rightMotor] = -speed;
				wait1Msec(1);
			}
			stopMotor(200);
	}

void stopMotor(int interval)
{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			wait1Msec(interval);

}
