#pragma config(StandardModel, "RVW REMBOT")
#pragma config(RenamedStdModelMotor, motorB, B)
#pragma config(RenamedStdModelMotor, motorC, C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int a=0;
int velocity =69;
void turntotheleft()
 {
   motor[B]=velocity;
	motor[C]=0;
	wait10Msec(130);
	 nMotorEncoder[B]=0;
		while(nMotorEncoder[B]<550|| nMotorEncoder[C]<550)
	{
	motor[C]=velocity;
	motor[B]=velocity;
	wait10Msec(1);
	}
	  motor[B]=velocity;
	motor[C]=0;
	wait10Msec(125);
		motor[C]=0;
	motor[B]=0;
}
void turntotheright()
 {
   motor[B]=0;
	motor[C]=velocity;
	wait10Msec(130);
	 nMotorEncoder[C]=0;
	while(nMotorEncoder[B]<500|| nMotorEncoder[C]<500)
	{
	motor[C]=velocity;
	motor[B]=velocity;
	wait10Msec(1);
	}
	 motor[B]=0;
	motor[C]=velocity;
	wait10Msec(125);
		motor[C]=0;
	motor[B]=0;
}

void goforward1()
{
	nMotorEncoder[B]=0;
   nMotorEncoder[C]=0;
	while(nMotorEncoder[C]<1050|| nMotorEncoder[B]<1050)
	{
	motor[C]=velocity;
	motor[B]=velocity;
	wait10Msec(1);
	}
			motor[C]=0;
	motor[B]=0;
}
void goforward2()
{
	nMotorEncoder[B]=0;
   nMotorEncoder[C]=0;
	while(nMotorEncoder[C]<450|| nMotorEncoder[B]<450)
	{
	motor[C]=velocity;
	motor[B]=velocity;
	wait10Msec(1);
	}
			motor[C]=0;
	motor[B]=0;
}
task main()
{
	nMotorEncoder[B]=0;
  nMotorEncoder[C]=0;
	while(nMotorEncoder[C]<250|| nMotorEncoder[B]<250)
	{
	motor[C]=velocity;
	motor[B]=velocity;
	wait10Msec(1);
	}
	motor[C]=0;
	motor[B]=0;
 	motor[B]=0;
	motor[C]=velocity;
	wait10Msec(125);
	goforward1();
	while(a<2)
	{
	turntotheleft();
	goforward1();
	turntotheright();
	goforward1();
	a++;
	}
 	motor[B]=velocity;
	motor[C]=0;
	wait10Msec(125);
}


