#pragma config(StandardModel, "RVW REMBOT")
#pragma config(RenamedStdModelMotor, motorB, right)
#pragma config(RenamedStdModelMotor, motorC, left)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int a=0;
int velocity =69;
void turntotheleft()
 {
   motor[right]=velocity;
	motor[left]=0;
	wait10Msec(130);
	 nMotorEncoder[right]=0;
		while(nMotorEncoder[right]<550|| nMotorEncoder[left]<550)
	{
	motor[left]=velocity;
	motor[right]=velocity;
	wait10Msec(1);
	}
	  motor[right]=velocity;
	motor[left]=0;
	wait10Msec(125);
		motor[left]=0;
	motor[right]=0;
}
void turntotheright()
 {
   motor[right]=0;
	motor[left]=velocity;
	wait10Msec(130);
	 nMotorEncoder[left]=0;
	while(nMotorEncoder[right]<500|| nMotorEncoder[left]<500)
	{
	motor[left]=velocity;
	motor[right]=velocity;
	wait10Msec(1);
	}
	 motor[right]=0;
	motor[left]=velocity;
	wait10Msec(125);
		motor[left]=0;
	motor[right]=0;
}

void goforward1()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<1050|| nMotorEncoder[right]<1050)
	{
	motor[left]=velocity;
	motor[right]=velocity;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
void goforward2()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<450|| nMotorEncoder[right]<450)
	{
	motor[left]=velocity;
	motor[right]=velocity;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
task main()
{
	nMotorEncoder[right]=0;
  nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<250|| nMotorEncoder[right]<250)
	{
	motor[left]=velocity;
	motor[right]=velocity;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
 	motor[right]=0;
	motor[left]=velocity;
	wait10Msec(125);
	goforward1();
	while(a<2)
	{
	turntotheleft();
	goforawrd1();
	turntotheright();
	goforward1();
	a++;
	}
 	motor[right]=velocity;
	motor[left]=0;
	wait10Msec(125);
}
