#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int x=0;
int motorSpeed =75;
void rightTurn()
 {
   motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(125);
	 nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<500|| nMotorEncoder[right]<500)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
	 motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(122);
		motor[left]=0;
	motor[right]=0;
}
void leftTurn()
 {
   motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(125);
	 nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
		while(nMotorEncoder[left]<550|| nMotorEncoder[right]<550)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
	  motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(122);
		motor[left]=0;
	motor[right]=0;
}
void forward()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<450|| nMotorEncoder[right]<450)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
void forward2()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<1050|| nMotorEncoder[right]<1050)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
task main()
{
	nMotorEncoder[right]=0;
  nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<250|| nMotorEncoder[right]<250)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
 	motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(125);
	forward();
	while(x<2)
	{
	leftTurn();
	forward2();
	rightTurn();
	forward2();
	//TurnLeft();
	//MoveForwardB();
	//TurnRight();
	x++;
	}
 	motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(125);
}
