#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Brians comments
// Main should be the top most method as that represents the behavior of this class. 
// Everything else , all other functions are to support what main has to achieve
// I should be able to read main without knwoing much about the details of the robot or its commands
// and be able to understand what main is doing
// These should be english like so that it is easy to understand
// What I should be seeing in main is commands such as turnLeftinWideArc, turnRightinWideArc etc.
// Please come up with your own names. For the fucntions too, each function should do one thing and
// the function name should communicate the intent of the function.
// actual robot commands such as nmotorEncoder etc should be wrapped in these functions so that it 
// is not necessary for a user of your class to understand the intimate details of turning to use your class



int x=0;
int motorSpeed =75;
void rightTurn()
 {
   motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(125);
	 nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<500|| nMotorEncoder[right]<500)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
	 motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(122);
		motor[left]=0;
	motor[right]=0;
}
void leftTurn()
 {
   motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(125);
	 nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
		while(nMotorEncoder[left]<550|| nMotorEncoder[right]<550)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
	  motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(122);
		motor[left]=0;
	motor[right]=0;
}
void forward()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<450|| nMotorEncoder[right]<450)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
void forward2()
{
	nMotorEncoder[right]=0;
   nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<1050|| nMotorEncoder[right]<1050)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
}
task main()
{
	nMotorEncoder[right]=0;
  nMotorEncoder[left]=0;
	while(nMotorEncoder[left]<250|| nMotorEncoder[right]<250)
	{
	motor[left]=motorSpeed;
	motor[right]=motorSpeed;
	wait10Msec(1);
	}
			motor[left]=0;
	motor[right]=0;
 	motor[right]=0;
	motor[left]=motorSpeed;
	wait10Msec(125);
	forward();
	while(x<2)
	{
	leftTurn();
	forward2();
	rightTurn();
	forward2();
	x++;
	}
 	motor[right]=motorSpeed;
	motor[left]=0;
	wait10Msec(125);
}
