#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int motorSpeed = 75;
	motor[left] = motorSpeed;
	motor[right] = motorSpeed;
	wait10Msec(500);
}
