#pragma config(StandardModel, "RVW MANTIS")
#pragma config(RenamedStdModelMotor, motorB, leftMotor)
#pragma config(RenamedStdModelMotor, motorC, rightMotor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()			//starts the code for the Labyrinth Challenge
{
	nSyncedMotors = synchBC;

	motor[leftMotor] = 100;			//gives the left motor at 100% power to move forward
	motor[rightMotor] = 100;			//gives the right motor at 100% power to move forward
	wait10Msec(350);			//does the code above for 3.5 seconds

	motor[leftMotor] = 50;			//gives the left motor 50% power to execute the left turn
	motor[rightMotor] = -50;			//gives the right motor -50% power to execute the left turn
	wait10Msec(95);			//does the following code for 950 milliseconds

	motor[leftMotor] = 100;			//gives the motor 100% power to move forward
	motor[rightMotor] = 100;			//gives the motor 100% power to move forward
	wait10Msec(210);			//does the code above for 2.1 seconds

	motor[leftMotor] = -50;			//gives the left motor -50% power to execute the right turn
	motor[rightMotor] = 50;			//gives the right motor 50% power to execute the right turn
	wait10Msec(95);			//does the code above for 950 milliseconds

	motor[leftMotor] = 100;			//gives the left motor 50% power to move forward
	motor[rightMotor] = 100;			//gives the right motor 50% power to move forward
	wait10Msec(100);			//does the code above for 1 second

	motor[leftMotor] = -50;			//gives the left motor -50% power to execute the right turn
	motor[rightMotor] = 50;			//gives the right motor 50% power to execute the right turn
	wait10Msec(95);			//does the code above for 950 milliseconds

	motor[leftMotor] = 100;			//gives the left motor 100% power to go forward
	motor[rightMotor] = 100;			//gives the right motor 100% power to go forward
	wait10Msec(100);			//does the code above for 1 second

	}			//Ends the code for the Labyrinth challenge
