#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "NewFile_Template003.c"

//task main ()
//{

//	nMotorEncoder[motorB]=0;
//	moveForward (1800);
//	turnRight ();
//	nMotorEncoder[motorB]=0;
//	moveForward (1800);
//	turnRight ();
//	nMotorEncoder[motorB]=0;
//	moveForward (1800);
//	turnRight ();
//	nMotorEncoder[motorB]=0;
//	moveForward (1800);
//	turnRight ();
//}



//void moveForward (int distanceInInches)
//{	nMotorEncoder[motorB] = distanceInInches;

//			while (nMotorEncoder[motorB] != 1820) //I would've used distanceInInches here, but for some reason VW was bugging, so for the sake of it, I put nMotorEncoder
//				{
//					motor[motorB]=50;
//					motor[motorC]=50;
//				}
//					turnRight();
//}

//void turnRight()
//{
//				while (nMotorEncoder[motorB] != 1854)
//				{
//						motor[motorB]=0;
//						motor[motorC]=50;
//					}

//}


task main()
{
for(int i = 1; i <= 4; i++)
{
	moveForward(24

	);
	turnRight();
}
}
