#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int motorspeed;

	motorspeed = 50;

	motor[leftMotor] = motorspeed;
	motor[rightMotor] = -motorspeed;
	wait1Msec(450);

	while (SensorValue[touch] == 0)
	{
		motor[rightMotor] = motorspeed;
		motor[leftMotor] =  motorspeed;
	}

	motor[rightMotor] = motorspeed;
	motor[leftMotor] = -motorspeed;
	wait1Msec(1100);

	while (SensorValue[touch] == 0)
	{
		motor[rightMotor] = motorspeed;
		motor[leftMotor] =  motorspeed;
	}

	motor[rightMotor] = -motorspeed;
	motor[leftMotor] = motorspeed;
	wait1Msec(1200);


	motor[rightMotor] = motorspeed;
	motor[leftMotor] =  motorspeed;
	wait1Msec(3000);

	motor[rightMotor] = -motorspeed;
	motor[leftMotor] = motorspeed;
	wait1Msec(200);

	while (SensorValue[touch] == 0)
	{
		motor[rightMotor] = motorspeed;
		motor[leftMotor] =  motorspeed;
	}

	motor[rightMotor] = motorspeed;
	motor[leftMotor] = -motorspeed;
	wait1Msec(1100);

	motor[rightMotor] = motorspeed;
	motor[leftMotor] =  motorspeed;
	wait1Msec(2000);

	motor[rightMotor] = motorspeed;
	motor[leftMotor] = -motorspeed;
	wait1Msec(250);

	while (SensorValue[touch] == 0)
	{
		motor[rightMotor] = motorspeed;
		motor[leftMotor] =  motorspeed;
	}

	motor[rightMotor] = -motorspeed;
	motor[leftMotor] = motorspeed;
	wait1Msec(1200);

		while (SensorValue[touch] == 0)
	{
		motor[rightMotor] = motorspeed;
		motor[leftMotor] =  motorspeed;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

	}
