#pragma config(StandardModel, "REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void oneset(int rotation)
{

	int motorspeed;

	motorspeed = 80;

	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while (nMotorEncoder[motorB] < 1800)
	{
		motor[motorB] = motorspeed;
		motor[motorC] = motorspeed;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;

	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while (nMotorEncoder[motorC] < rotation)
	{
		motor[motorB] = -motorspeed;
		motor[motorC] =  motorspeed;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;

}

task main()
{
	int rot;

	rot = 200;
	oneset(rot);
	oneset(rot);
	oneset(rot);
	oneset(rot);
	motor[rightMotor]=50;
	motor[leftMotor]=-50;
	wait1Msec(40);
	oneset(rot);
	motor[rightMotor]=50;
	motor[leftMotor]=-50;
	wait1Msec(100);
	oneset(rot);
	motor[rightMotor]=50;
	motor[leftMotor]=-50;
	wait1Msec(100);
	oneset(rot);
	motor[rightMotor]=50;
	motor[leftMotor]=-50;
	wait1Msec(100);
	oneset(rot);
}
