#pragma config(StandardModel, "REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int constant;

	constant=1;
	while (constant==1)
	{
		while (SensorValue[S4] > 100)
		{
			motor[rightMotor] = 100;
			motor[leftMotor] = -100;
		}

		while (SensorValue[S4] < 100)
		{
			while (SensorValue[S1] != 1 && SensorValue[S4] < 100)
			{
				motor[rightMotor] = 100;
				motor[leftMotor] = 100;
			}
			while (SensorValue[S1] == 1)
			{
				motor[rightMotor] = 100;
				motor[leftMotor] = 100;
			}
			while (SensorValue[S1] != 1 && SensorValue[S4] < 100)
			{
				motor[rightMotor] = 100;
				motor[leftMotor] = -100;
			}

		}
	}

}
