#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard                !!*//
// This is for the NXT model, not TETRIX
/*
*/
/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

void moveForward (int distanceInInches);
void turnRight ();
void turnLeft ();

task main()
{
}

void moveForward (int distanceInInches)
{
	while ( nMotorEncoder[rightMotor] < (distanceInInches/0.01924))
	{
		motor[rightMotor] = 50;
		motor[leftMotor] = 50;
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
}

void turnRight ()
{
	while (nMotorEncoder[rightMotor] > -153)
	{
		motor[rightMotor] = -50;
		motor[leftMotor] = 50;
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

}

void turnLeft ()
{
		while (nMotorEncoder[rightMotor] < 153)
	{
		motor[rightMotor] = 50;
		motor[leftMotor] = -50;
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

}
